export const styles = {
  FontAndroidHeadingDisplay1: {
    fontSize: 45,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 52,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidHeadingDisplay2: {
    fontSize: 36,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 44,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidHeadingH1: {
    fontSize: 32,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 40,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidHeadingH2: {
    fontSize: 28,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 36,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidHeadingH3: {
    fontSize: 22,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidHeadingH4: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidLargeRegular: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidLargeSemibold: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidDefaultRegular: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidDefaultSemibold: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidSmallRegular: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.2,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidSmallSemibold: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.2,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidXSmallRegular: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.2,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidXSmallSemibold: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "Roboto Flex",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.2,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidMonospaceLarge: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Roboto Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidMonospaceDefault: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Roboto Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontAndroidMonospaceSmall: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Roboto Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMacosLargeRegular: {
    fontSize: 15,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.08,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMacosLargeSemibold: {
    fontSize: 15,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.08,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMacosDefaultRegular: {
    fontSize: 13,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.08,
    lineHeight: 15.6,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMacosDefaultSemibold: {
    fontSize: 13,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.08,
    lineHeight: 15.6,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMacosSmallRegular: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.29,
    lineHeight: 14.4,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMacosSmallSemibold: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.29,
    lineHeight: 14.4,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontWindowsLargeRegular: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Segoe UI Variable",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 19.2,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontWindowsLargeSemibold: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Segoe UI Variable",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 19.2,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontWindowsDefaultRegular: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Segoe UI Variable",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 16.8,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontWindowsDefaultSemibold: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Segoe UI Variable",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 16.8,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontWindowsSmallRegular: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Segoe UI Variable",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 14.4,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontWindowsSmallSemibold: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Segoe UI Variable",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 14.4,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosHeadingDisplay1: {
    fontSize: 44,
    textDecoration: "none",
    fontFamily: "SF Pro Display",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 52,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosHeadingDisplay2: {
    fontSize: 36,
    textDecoration: "none",
    fontFamily: "SF Pro Display",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 44,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosHeadingH1: {
    fontSize: 32,
    textDecoration: "none",
    fontFamily: "SF Pro Display",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.37,
    lineHeight: 40,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosHeadingH2: {
    fontSize: 28,
    textDecoration: "none",
    fontFamily: "SF Pro Display",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.36,
    lineHeight: 34,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosHeadingH3: {
    fontSize: 22,
    textDecoration: "none",
    fontFamily: "SF Pro Display",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.35,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosHeadingH4: {
    fontSize: 17,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.41,
    lineHeight: 22,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosLargeRegular: {
    fontSize: 17,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.41,
    lineHeight: 22,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosLargeSemibold: {
    fontSize: 17,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.41,
    lineHeight: 22,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosDefaultRegular: {
    fontSize: 15,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.24,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosDefaultSemibold: {
    fontSize: 15,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.24,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosSmallRegular: {
    fontSize: 13,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.08,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosSmallSemibold: {
    fontSize: 13,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: -0.08,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosXSmallRegular: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.07,
    lineHeight: 13,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosXSmallSemibold: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "SF Pro Text",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.07,
    lineHeight: 13,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosMonospaceLarge: {
    fontSize: 17,
    textDecoration: "none",
    fontFamily: "SF Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 22,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosMonospaceDefault: {
    fontSize: 15,
    textDecoration: "none",
    fontFamily: "SF Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontIosMonospaceSmall: {
    fontSize: 13,
    textDecoration: "none",
    fontFamily: "SF Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopHeadingDisplay1: {
    fontSize: 52,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 78,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopHeadingDisplay2: {
    fontSize: 36,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 54,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopHeadingH1: {
    fontSize: 32,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 48,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopHeadingH2: {
    fontSize: 28,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 40,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopHeadingH3: {
    fontSize: 22,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 32,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopHeadingH4: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopPrimaryLargeRegular: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopPrimaryLargeSemibold: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopPrimaryDefaultRegular: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopPrimaryDefaultSemibold: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopPrimarySmallRegular: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopPrimarySmallSemibold: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopPrimaryXSmallRegular: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopPrimaryXSmallSemibold: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopSecondaryLargeRegular: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Manrope",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopSecondaryLargeSemibold: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Manrope",
    fontWeight: 700,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopSecondaryDefaultRegular: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Manrope",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopSecondaryDefaultSemibold: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Manrope",
    fontWeight: 700,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopSecondarySmallRegular: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Manrope",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopSecondarySmallSemibold: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Manrope",
    fontWeight: 700,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopSecondaryXSmallDefault: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "Manrope",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopSecondaryXSmallSemibold: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "Manrope",
    fontWeight: 700,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopMonospaceLarge: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "DM Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopMonospaceDefault: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "DM Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontDesktopMonospaceSmall: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "DM Mono",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMobileDisplayDisplay1: {
    fontSize: 32,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 48,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMobileDisplayDisplay2: {
    fontSize: 28,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 42,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMobileHeadingH1: {
    fontSize: 28,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 40,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMobileHeadingH2: {
    fontSize: 22,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 32,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMobileHeadingH3: {
    fontSize: 18,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontMobileHeadingH4: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontComponentsLabel: {
    fontSize: 11,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.22,
    lineHeight: 13.2,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontComponentsTableheader: {
    fontSize: 13,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontComponentsNavbutton: {
    fontSize: 15,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.3,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontComponentsButtonSmall: {
    fontSize: 12,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.36,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontComponentsButtonDefault: {
    fontSize: 13,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.39,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontComponentsButtonLarge: {
    fontSize: 14,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.28,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  FontComponentsButtonJumbo: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Poppins",
    fontWeight: 600,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0.16,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  TypographyAndroidHeadingDisplay1FontSize: 45,
  TypographyAndroidHeadingDisplay1TextDecoration: "none",
  TypographyAndroidHeadingDisplay1FontFamily: "Roboto Flex",
  TypographyAndroidHeadingDisplay1FontWeight: 500,
  TypographyAndroidHeadingDisplay1FontStyle: "normal",
  TypographyAndroidHeadingDisplay1FontStretch: "normal",
  TypographyAndroidHeadingDisplay1LetterSpacing: 0,
  TypographyAndroidHeadingDisplay1LineHeight: 52,
  TypographyAndroidHeadingDisplay1ParagraphIndent: 0,
  TypographyAndroidHeadingDisplay1ParagraphSpacing: 0,
  TypographyAndroidHeadingDisplay1TextCase: "none",
  TypographyAndroidHeadingDisplay2FontSize: 36,
  TypographyAndroidHeadingDisplay2TextDecoration: "none",
  TypographyAndroidHeadingDisplay2FontFamily: "Roboto Flex",
  TypographyAndroidHeadingDisplay2FontWeight: 500,
  TypographyAndroidHeadingDisplay2FontStyle: "normal",
  TypographyAndroidHeadingDisplay2FontStretch: "normal",
  TypographyAndroidHeadingDisplay2LetterSpacing: 0,
  TypographyAndroidHeadingDisplay2LineHeight: 44,
  TypographyAndroidHeadingDisplay2ParagraphIndent: 0,
  TypographyAndroidHeadingDisplay2ParagraphSpacing: 0,
  TypographyAndroidHeadingDisplay2TextCase: "none",
  TypographyAndroidHeadingH1FontSize: 32,
  TypographyAndroidHeadingH1TextDecoration: "none",
  TypographyAndroidHeadingH1FontFamily: "Roboto Flex",
  TypographyAndroidHeadingH1FontWeight: 500,
  TypographyAndroidHeadingH1FontStyle: "normal",
  TypographyAndroidHeadingH1FontStretch: "normal",
  TypographyAndroidHeadingH1LetterSpacing: 0,
  TypographyAndroidHeadingH1LineHeight: 40,
  TypographyAndroidHeadingH1ParagraphIndent: 0,
  TypographyAndroidHeadingH1ParagraphSpacing: 0,
  TypographyAndroidHeadingH1TextCase: "none",
  TypographyAndroidHeadingH2FontSize: 28,
  TypographyAndroidHeadingH2TextDecoration: "none",
  TypographyAndroidHeadingH2FontFamily: "Roboto Flex",
  TypographyAndroidHeadingH2FontWeight: 500,
  TypographyAndroidHeadingH2FontStyle: "normal",
  TypographyAndroidHeadingH2FontStretch: "normal",
  TypographyAndroidHeadingH2LetterSpacing: 0,
  TypographyAndroidHeadingH2LineHeight: 36,
  TypographyAndroidHeadingH2ParagraphIndent: 0,
  TypographyAndroidHeadingH2ParagraphSpacing: 0,
  TypographyAndroidHeadingH2TextCase: "none",
  TypographyAndroidHeadingH3FontSize: 22,
  TypographyAndroidHeadingH3TextDecoration: "none",
  TypographyAndroidHeadingH3FontFamily: "Roboto Flex",
  TypographyAndroidHeadingH3FontWeight: 500,
  TypographyAndroidHeadingH3FontStyle: "normal",
  TypographyAndroidHeadingH3FontStretch: "normal",
  TypographyAndroidHeadingH3LetterSpacing: 0,
  TypographyAndroidHeadingH3LineHeight: 28,
  TypographyAndroidHeadingH3ParagraphIndent: 0,
  TypographyAndroidHeadingH3ParagraphSpacing: 0,
  TypographyAndroidHeadingH3TextCase: "none",
  TypographyAndroidHeadingH4FontSize: 16,
  TypographyAndroidHeadingH4TextDecoration: "none",
  TypographyAndroidHeadingH4FontFamily: "Roboto Flex",
  TypographyAndroidHeadingH4FontWeight: 600,
  TypographyAndroidHeadingH4FontStyle: "normal",
  TypographyAndroidHeadingH4FontStretch: "normal",
  TypographyAndroidHeadingH4LetterSpacing: 0,
  TypographyAndroidHeadingH4LineHeight: 24,
  TypographyAndroidHeadingH4ParagraphIndent: 0,
  TypographyAndroidHeadingH4ParagraphSpacing: 0,
  TypographyAndroidHeadingH4TextCase: "none",
  TypographyAndroidLargeRegularFontSize: 16,
  TypographyAndroidLargeRegularTextDecoration: "none",
  TypographyAndroidLargeRegularFontFamily: "Roboto Flex",
  TypographyAndroidLargeRegularFontWeight: 400,
  TypographyAndroidLargeRegularFontStyle: "normal",
  TypographyAndroidLargeRegularFontStretch: "normal",
  TypographyAndroidLargeRegularLetterSpacing: 0,
  TypographyAndroidLargeRegularLineHeight: 24,
  TypographyAndroidLargeRegularParagraphIndent: 0,
  TypographyAndroidLargeRegularParagraphSpacing: 0,
  TypographyAndroidLargeRegularTextCase: "none",
  TypographyAndroidLargeSemiboldFontSize: 16,
  TypographyAndroidLargeSemiboldTextDecoration: "none",
  TypographyAndroidLargeSemiboldFontFamily: "Roboto Flex",
  TypographyAndroidLargeSemiboldFontWeight: 600,
  TypographyAndroidLargeSemiboldFontStyle: "normal",
  TypographyAndroidLargeSemiboldFontStretch: "normal",
  TypographyAndroidLargeSemiboldLetterSpacing: 0,
  TypographyAndroidLargeSemiboldLineHeight: 24,
  TypographyAndroidLargeSemiboldParagraphIndent: 0,
  TypographyAndroidLargeSemiboldParagraphSpacing: 0,
  TypographyAndroidLargeSemiboldTextCase: "none",
  TypographyAndroidDefaultRegularFontSize: 14,
  TypographyAndroidDefaultRegularTextDecoration: "none",
  TypographyAndroidDefaultRegularFontFamily: "Roboto Flex",
  TypographyAndroidDefaultRegularFontWeight: 400,
  TypographyAndroidDefaultRegularFontStyle: "normal",
  TypographyAndroidDefaultRegularFontStretch: "normal",
  TypographyAndroidDefaultRegularLetterSpacing: 0,
  TypographyAndroidDefaultRegularLineHeight: 20,
  TypographyAndroidDefaultRegularParagraphIndent: 0,
  TypographyAndroidDefaultRegularParagraphSpacing: 0,
  TypographyAndroidDefaultRegularTextCase: "none",
  TypographyAndroidDefaultSemiboldFontSize: 14,
  TypographyAndroidDefaultSemiboldTextDecoration: "none",
  TypographyAndroidDefaultSemiboldFontFamily: "Roboto Flex",
  TypographyAndroidDefaultSemiboldFontWeight: 600,
  TypographyAndroidDefaultSemiboldFontStyle: "normal",
  TypographyAndroidDefaultSemiboldFontStretch: "normal",
  TypographyAndroidDefaultSemiboldLetterSpacing: 0,
  TypographyAndroidDefaultSemiboldLineHeight: 20,
  TypographyAndroidDefaultSemiboldParagraphIndent: 0,
  TypographyAndroidDefaultSemiboldParagraphSpacing: 0,
  TypographyAndroidDefaultSemiboldTextCase: "none",
  TypographyAndroidSmallRegularFontSize: 12,
  TypographyAndroidSmallRegularTextDecoration: "none",
  TypographyAndroidSmallRegularFontFamily: "Roboto Flex",
  TypographyAndroidSmallRegularFontWeight: 400,
  TypographyAndroidSmallRegularFontStyle: "normal",
  TypographyAndroidSmallRegularFontStretch: "normal",
  TypographyAndroidSmallRegularLetterSpacing: 0.2,
  TypographyAndroidSmallRegularLineHeight: 16,
  TypographyAndroidSmallRegularParagraphIndent: 0,
  TypographyAndroidSmallRegularParagraphSpacing: 0,
  TypographyAndroidSmallRegularTextCase: "none",
  TypographyAndroidSmallSemiboldFontSize: 12,
  TypographyAndroidSmallSemiboldTextDecoration: "none",
  TypographyAndroidSmallSemiboldFontFamily: "Roboto Flex",
  TypographyAndroidSmallSemiboldFontWeight: 600,
  TypographyAndroidSmallSemiboldFontStyle: "normal",
  TypographyAndroidSmallSemiboldFontStretch: "normal",
  TypographyAndroidSmallSemiboldLetterSpacing: 0.2,
  TypographyAndroidSmallSemiboldLineHeight: 16,
  TypographyAndroidSmallSemiboldParagraphIndent: 0,
  TypographyAndroidSmallSemiboldParagraphSpacing: 0,
  TypographyAndroidSmallSemiboldTextCase: "none",
  TypographyAndroidXSmallRegularFontSize: 11,
  TypographyAndroidXSmallRegularTextDecoration: "none",
  TypographyAndroidXSmallRegularFontFamily: "Roboto Flex",
  TypographyAndroidXSmallRegularFontWeight: 400,
  TypographyAndroidXSmallRegularFontStyle: "normal",
  TypographyAndroidXSmallRegularFontStretch: "normal",
  TypographyAndroidXSmallRegularLetterSpacing: 0.2,
  TypographyAndroidXSmallRegularLineHeight: 16,
  TypographyAndroidXSmallRegularParagraphIndent: 0,
  TypographyAndroidXSmallRegularParagraphSpacing: 0,
  TypographyAndroidXSmallRegularTextCase: "none",
  TypographyAndroidXSmallSemiboldFontSize: 11,
  TypographyAndroidXSmallSemiboldTextDecoration: "none",
  TypographyAndroidXSmallSemiboldFontFamily: "Roboto Flex",
  TypographyAndroidXSmallSemiboldFontWeight: 600,
  TypographyAndroidXSmallSemiboldFontStyle: "normal",
  TypographyAndroidXSmallSemiboldFontStretch: "normal",
  TypographyAndroidXSmallSemiboldLetterSpacing: 0.2,
  TypographyAndroidXSmallSemiboldLineHeight: 16,
  TypographyAndroidXSmallSemiboldParagraphIndent: 0,
  TypographyAndroidXSmallSemiboldParagraphSpacing: 0,
  TypographyAndroidXSmallSemiboldTextCase: "none",
  TypographyAndroidMonospaceLargeFontSize: 16,
  TypographyAndroidMonospaceLargeTextDecoration: "none",
  TypographyAndroidMonospaceLargeFontFamily: "Roboto Mono",
  TypographyAndroidMonospaceLargeFontWeight: 400,
  TypographyAndroidMonospaceLargeFontStyle: "normal",
  TypographyAndroidMonospaceLargeFontStretch: "normal",
  TypographyAndroidMonospaceLargeLetterSpacing: 0,
  TypographyAndroidMonospaceLargeLineHeight: 24,
  TypographyAndroidMonospaceLargeParagraphIndent: 0,
  TypographyAndroidMonospaceLargeParagraphSpacing: 0,
  TypographyAndroidMonospaceLargeTextCase: "none",
  TypographyAndroidMonospaceDefaultFontSize: 14,
  TypographyAndroidMonospaceDefaultTextDecoration: "none",
  TypographyAndroidMonospaceDefaultFontFamily: "Roboto Mono",
  TypographyAndroidMonospaceDefaultFontWeight: 400,
  TypographyAndroidMonospaceDefaultFontStyle: "normal",
  TypographyAndroidMonospaceDefaultFontStretch: "normal",
  TypographyAndroidMonospaceDefaultLetterSpacing: 0,
  TypographyAndroidMonospaceDefaultLineHeight: 20,
  TypographyAndroidMonospaceDefaultParagraphIndent: 0,
  TypographyAndroidMonospaceDefaultParagraphSpacing: 0,
  TypographyAndroidMonospaceDefaultTextCase: "none",
  TypographyAndroidMonospaceSmallFontSize: 12,
  TypographyAndroidMonospaceSmallTextDecoration: "none",
  TypographyAndroidMonospaceSmallFontFamily: "Roboto Mono",
  TypographyAndroidMonospaceSmallFontWeight: 400,
  TypographyAndroidMonospaceSmallFontStyle: "normal",
  TypographyAndroidMonospaceSmallFontStretch: "normal",
  TypographyAndroidMonospaceSmallLetterSpacing: 0,
  TypographyAndroidMonospaceSmallLineHeight: 16,
  TypographyAndroidMonospaceSmallParagraphIndent: 0,
  TypographyAndroidMonospaceSmallParagraphSpacing: 0,
  TypographyAndroidMonospaceSmallTextCase: "none",
  TypographyMacosLargeRegularFontSize: 15,
  TypographyMacosLargeRegularTextDecoration: "none",
  TypographyMacosLargeRegularFontFamily: "SF Pro Text",
  TypographyMacosLargeRegularFontWeight: 400,
  TypographyMacosLargeRegularFontStyle: "normal",
  TypographyMacosLargeRegularFontStretch: "normal",
  TypographyMacosLargeRegularLetterSpacing: -0.08,
  TypographyMacosLargeRegularLineHeight: 18,
  TypographyMacosLargeRegularParagraphIndent: 0,
  TypographyMacosLargeRegularParagraphSpacing: 0,
  TypographyMacosLargeRegularTextCase: "none",
  TypographyMacosLargeSemiboldFontSize: 15,
  TypographyMacosLargeSemiboldTextDecoration: "none",
  TypographyMacosLargeSemiboldFontFamily: "SF Pro Text",
  TypographyMacosLargeSemiboldFontWeight: 600,
  TypographyMacosLargeSemiboldFontStyle: "normal",
  TypographyMacosLargeSemiboldFontStretch: "normal",
  TypographyMacosLargeSemiboldLetterSpacing: -0.08,
  TypographyMacosLargeSemiboldLineHeight: 18,
  TypographyMacosLargeSemiboldParagraphIndent: 0,
  TypographyMacosLargeSemiboldParagraphSpacing: 0,
  TypographyMacosLargeSemiboldTextCase: "none",
  TypographyMacosDefaultRegularFontSize: 13,
  TypographyMacosDefaultRegularTextDecoration: "none",
  TypographyMacosDefaultRegularFontFamily: "SF Pro Text",
  TypographyMacosDefaultRegularFontWeight: 400,
  TypographyMacosDefaultRegularFontStyle: "normal",
  TypographyMacosDefaultRegularFontStretch: "normal",
  TypographyMacosDefaultRegularLetterSpacing: -0.08,
  TypographyMacosDefaultRegularLineHeight: 15.6,
  TypographyMacosDefaultRegularParagraphIndent: 0,
  TypographyMacosDefaultRegularParagraphSpacing: 0,
  TypographyMacosDefaultRegularTextCase: "none",
  TypographyMacosDefaultSemiboldFontSize: 13,
  TypographyMacosDefaultSemiboldTextDecoration: "none",
  TypographyMacosDefaultSemiboldFontFamily: "SF Pro Text",
  TypographyMacosDefaultSemiboldFontWeight: 600,
  TypographyMacosDefaultSemiboldFontStyle: "normal",
  TypographyMacosDefaultSemiboldFontStretch: "normal",
  TypographyMacosDefaultSemiboldLetterSpacing: -0.08,
  TypographyMacosDefaultSemiboldLineHeight: 15.6,
  TypographyMacosDefaultSemiboldParagraphIndent: 0,
  TypographyMacosDefaultSemiboldParagraphSpacing: 0,
  TypographyMacosDefaultSemiboldTextCase: "none",
  TypographyMacosSmallRegularFontSize: 12,
  TypographyMacosSmallRegularTextDecoration: "none",
  TypographyMacosSmallRegularFontFamily: "SF Pro Text",
  TypographyMacosSmallRegularFontWeight: 400,
  TypographyMacosSmallRegularFontStyle: "normal",
  TypographyMacosSmallRegularFontStretch: "normal",
  TypographyMacosSmallRegularLetterSpacing: -0.29,
  TypographyMacosSmallRegularLineHeight: 14.4,
  TypographyMacosSmallRegularParagraphIndent: 0,
  TypographyMacosSmallRegularParagraphSpacing: 0,
  TypographyMacosSmallRegularTextCase: "none",
  TypographyMacosSmallSemiboldFontSize: 12,
  TypographyMacosSmallSemiboldTextDecoration: "none",
  TypographyMacosSmallSemiboldFontFamily: "SF Pro Text",
  TypographyMacosSmallSemiboldFontWeight: 600,
  TypographyMacosSmallSemiboldFontStyle: "normal",
  TypographyMacosSmallSemiboldFontStretch: "normal",
  TypographyMacosSmallSemiboldLetterSpacing: -0.29,
  TypographyMacosSmallSemiboldLineHeight: 14.4,
  TypographyMacosSmallSemiboldParagraphIndent: 0,
  TypographyMacosSmallSemiboldParagraphSpacing: 0,
  TypographyMacosSmallSemiboldTextCase: "none",
  TypographyWindowsLargeRegularFontSize: 16,
  TypographyWindowsLargeRegularTextDecoration: "none",
  TypographyWindowsLargeRegularFontFamily: "Segoe UI Variable",
  TypographyWindowsLargeRegularFontWeight: 400,
  TypographyWindowsLargeRegularFontStyle: "normal",
  TypographyWindowsLargeRegularFontStretch: "normal",
  TypographyWindowsLargeRegularLetterSpacing: 0,
  TypographyWindowsLargeRegularLineHeight: 19.2,
  TypographyWindowsLargeRegularParagraphIndent: 0,
  TypographyWindowsLargeRegularParagraphSpacing: 0,
  TypographyWindowsLargeRegularTextCase: "none",
  TypographyWindowsLargeSemiboldFontSize: 16,
  TypographyWindowsLargeSemiboldTextDecoration: "none",
  TypographyWindowsLargeSemiboldFontFamily: "Segoe UI Variable",
  TypographyWindowsLargeSemiboldFontWeight: 600,
  TypographyWindowsLargeSemiboldFontStyle: "normal",
  TypographyWindowsLargeSemiboldFontStretch: "normal",
  TypographyWindowsLargeSemiboldLetterSpacing: 0,
  TypographyWindowsLargeSemiboldLineHeight: 19.2,
  TypographyWindowsLargeSemiboldParagraphIndent: 0,
  TypographyWindowsLargeSemiboldParagraphSpacing: 0,
  TypographyWindowsLargeSemiboldTextCase: "none",
  TypographyWindowsDefaultRegularFontSize: 14,
  TypographyWindowsDefaultRegularTextDecoration: "none",
  TypographyWindowsDefaultRegularFontFamily: "Segoe UI Variable",
  TypographyWindowsDefaultRegularFontWeight: 400,
  TypographyWindowsDefaultRegularFontStyle: "normal",
  TypographyWindowsDefaultRegularFontStretch: "normal",
  TypographyWindowsDefaultRegularLetterSpacing: 0,
  TypographyWindowsDefaultRegularLineHeight: 16.8,
  TypographyWindowsDefaultRegularParagraphIndent: 0,
  TypographyWindowsDefaultRegularParagraphSpacing: 0,
  TypographyWindowsDefaultRegularTextCase: "none",
  TypographyWindowsDefaultSemiboldFontSize: 14,
  TypographyWindowsDefaultSemiboldTextDecoration: "none",
  TypographyWindowsDefaultSemiboldFontFamily: "Segoe UI Variable",
  TypographyWindowsDefaultSemiboldFontWeight: 600,
  TypographyWindowsDefaultSemiboldFontStyle: "normal",
  TypographyWindowsDefaultSemiboldFontStretch: "normal",
  TypographyWindowsDefaultSemiboldLetterSpacing: 0,
  TypographyWindowsDefaultSemiboldLineHeight: 16.8,
  TypographyWindowsDefaultSemiboldParagraphIndent: 0,
  TypographyWindowsDefaultSemiboldParagraphSpacing: 0,
  TypographyWindowsDefaultSemiboldTextCase: "none",
  TypographyWindowsSmallRegularFontSize: 12,
  TypographyWindowsSmallRegularTextDecoration: "none",
  TypographyWindowsSmallRegularFontFamily: "Segoe UI Variable",
  TypographyWindowsSmallRegularFontWeight: 400,
  TypographyWindowsSmallRegularFontStyle: "normal",
  TypographyWindowsSmallRegularFontStretch: "normal",
  TypographyWindowsSmallRegularLetterSpacing: 0,
  TypographyWindowsSmallRegularLineHeight: 14.4,
  TypographyWindowsSmallRegularParagraphIndent: 0,
  TypographyWindowsSmallRegularParagraphSpacing: 0,
  TypographyWindowsSmallRegularTextCase: "none",
  TypographyWindowsSmallSemiboldFontSize: 12,
  TypographyWindowsSmallSemiboldTextDecoration: "none",
  TypographyWindowsSmallSemiboldFontFamily: "Segoe UI Variable",
  TypographyWindowsSmallSemiboldFontWeight: 600,
  TypographyWindowsSmallSemiboldFontStyle: "normal",
  TypographyWindowsSmallSemiboldFontStretch: "normal",
  TypographyWindowsSmallSemiboldLetterSpacing: 0,
  TypographyWindowsSmallSemiboldLineHeight: 14.4,
  TypographyWindowsSmallSemiboldParagraphIndent: 0,
  TypographyWindowsSmallSemiboldParagraphSpacing: 0,
  TypographyWindowsSmallSemiboldTextCase: "none",
  TypographyIosHeadingDisplay1FontSize: 44,
  TypographyIosHeadingDisplay1TextDecoration: "none",
  TypographyIosHeadingDisplay1FontFamily: "SF Pro Display",
  TypographyIosHeadingDisplay1FontWeight: 500,
  TypographyIosHeadingDisplay1FontStyle: "normal",
  TypographyIosHeadingDisplay1FontStretch: "normal",
  TypographyIosHeadingDisplay1LetterSpacing: 0,
  TypographyIosHeadingDisplay1LineHeight: 52,
  TypographyIosHeadingDisplay1ParagraphIndent: 0,
  TypographyIosHeadingDisplay1ParagraphSpacing: 0,
  TypographyIosHeadingDisplay1TextCase: "none",
  TypographyIosHeadingDisplay2FontSize: 36,
  TypographyIosHeadingDisplay2TextDecoration: "none",
  TypographyIosHeadingDisplay2FontFamily: "SF Pro Display",
  TypographyIosHeadingDisplay2FontWeight: 500,
  TypographyIosHeadingDisplay2FontStyle: "normal",
  TypographyIosHeadingDisplay2FontStretch: "normal",
  TypographyIosHeadingDisplay2LetterSpacing: 0,
  TypographyIosHeadingDisplay2LineHeight: 44,
  TypographyIosHeadingDisplay2ParagraphIndent: 0,
  TypographyIosHeadingDisplay2ParagraphSpacing: 0,
  TypographyIosHeadingDisplay2TextCase: "none",
  TypographyIosHeadingH1FontSize: 32,
  TypographyIosHeadingH1TextDecoration: "none",
  TypographyIosHeadingH1FontFamily: "SF Pro Display",
  TypographyIosHeadingH1FontWeight: 500,
  TypographyIosHeadingH1FontStyle: "normal",
  TypographyIosHeadingH1FontStretch: "normal",
  TypographyIosHeadingH1LetterSpacing: 0.37,
  TypographyIosHeadingH1LineHeight: 40,
  TypographyIosHeadingH1ParagraphIndent: 0,
  TypographyIosHeadingH1ParagraphSpacing: 0,
  TypographyIosHeadingH1TextCase: "none",
  TypographyIosHeadingH2FontSize: 28,
  TypographyIosHeadingH2TextDecoration: "none",
  TypographyIosHeadingH2FontFamily: "SF Pro Display",
  TypographyIosHeadingH2FontWeight: 500,
  TypographyIosHeadingH2FontStyle: "normal",
  TypographyIosHeadingH2FontStretch: "normal",
  TypographyIosHeadingH2LetterSpacing: 0.36,
  TypographyIosHeadingH2LineHeight: 34,
  TypographyIosHeadingH2ParagraphIndent: 0,
  TypographyIosHeadingH2ParagraphSpacing: 0,
  TypographyIosHeadingH2TextCase: "none",
  TypographyIosHeadingH3FontSize: 22,
  TypographyIosHeadingH3TextDecoration: "none",
  TypographyIosHeadingH3FontFamily: "SF Pro Display",
  TypographyIosHeadingH3FontWeight: 500,
  TypographyIosHeadingH3FontStyle: "normal",
  TypographyIosHeadingH3FontStretch: "normal",
  TypographyIosHeadingH3LetterSpacing: 0.35,
  TypographyIosHeadingH3LineHeight: 28,
  TypographyIosHeadingH3ParagraphIndent: 0,
  TypographyIosHeadingH3ParagraphSpacing: 0,
  TypographyIosHeadingH3TextCase: "none",
  TypographyIosHeadingH4FontSize: 17,
  TypographyIosHeadingH4TextDecoration: "none",
  TypographyIosHeadingH4FontFamily: "SF Pro Text",
  TypographyIosHeadingH4FontWeight: 500,
  TypographyIosHeadingH4FontStyle: "normal",
  TypographyIosHeadingH4FontStretch: "normal",
  TypographyIosHeadingH4LetterSpacing: -0.41,
  TypographyIosHeadingH4LineHeight: 22,
  TypographyIosHeadingH4ParagraphIndent: 0,
  TypographyIosHeadingH4ParagraphSpacing: 0,
  TypographyIosHeadingH4TextCase: "none",
  TypographyIosLargeRegularFontSize: 17,
  TypographyIosLargeRegularTextDecoration: "none",
  TypographyIosLargeRegularFontFamily: "SF Pro Text",
  TypographyIosLargeRegularFontWeight: 400,
  TypographyIosLargeRegularFontStyle: "normal",
  TypographyIosLargeRegularFontStretch: "normal",
  TypographyIosLargeRegularLetterSpacing: -0.41,
  TypographyIosLargeRegularLineHeight: 22,
  TypographyIosLargeRegularParagraphIndent: 0,
  TypographyIosLargeRegularParagraphSpacing: 0,
  TypographyIosLargeRegularTextCase: "none",
  TypographyIosLargeSemiboldFontSize: 17,
  TypographyIosLargeSemiboldTextDecoration: "none",
  TypographyIosLargeSemiboldFontFamily: "SF Pro Text",
  TypographyIosLargeSemiboldFontWeight: 600,
  TypographyIosLargeSemiboldFontStyle: "normal",
  TypographyIosLargeSemiboldFontStretch: "normal",
  TypographyIosLargeSemiboldLetterSpacing: -0.41,
  TypographyIosLargeSemiboldLineHeight: 22,
  TypographyIosLargeSemiboldParagraphIndent: 0,
  TypographyIosLargeSemiboldParagraphSpacing: 0,
  TypographyIosLargeSemiboldTextCase: "none",
  TypographyIosDefaultRegularFontSize: 15,
  TypographyIosDefaultRegularTextDecoration: "none",
  TypographyIosDefaultRegularFontFamily: "SF Pro Text",
  TypographyIosDefaultRegularFontWeight: 400,
  TypographyIosDefaultRegularFontStyle: "normal",
  TypographyIosDefaultRegularFontStretch: "normal",
  TypographyIosDefaultRegularLetterSpacing: -0.24,
  TypographyIosDefaultRegularLineHeight: 20,
  TypographyIosDefaultRegularParagraphIndent: 0,
  TypographyIosDefaultRegularParagraphSpacing: 0,
  TypographyIosDefaultRegularTextCase: "none",
  TypographyIosDefaultSemiboldFontSize: 15,
  TypographyIosDefaultSemiboldTextDecoration: "none",
  TypographyIosDefaultSemiboldFontFamily: "SF Pro Text",
  TypographyIosDefaultSemiboldFontWeight: 600,
  TypographyIosDefaultSemiboldFontStyle: "normal",
  TypographyIosDefaultSemiboldFontStretch: "normal",
  TypographyIosDefaultSemiboldLetterSpacing: -0.24,
  TypographyIosDefaultSemiboldLineHeight: 20,
  TypographyIosDefaultSemiboldParagraphIndent: 0,
  TypographyIosDefaultSemiboldParagraphSpacing: 0,
  TypographyIosDefaultSemiboldTextCase: "none",
  TypographyIosSmallRegularFontSize: 13,
  TypographyIosSmallRegularTextDecoration: "none",
  TypographyIosSmallRegularFontFamily: "SF Pro Text",
  TypographyIosSmallRegularFontWeight: 400,
  TypographyIosSmallRegularFontStyle: "normal",
  TypographyIosSmallRegularFontStretch: "normal",
  TypographyIosSmallRegularLetterSpacing: -0.08,
  TypographyIosSmallRegularLineHeight: 18,
  TypographyIosSmallRegularParagraphIndent: 0,
  TypographyIosSmallRegularParagraphSpacing: 0,
  TypographyIosSmallRegularTextCase: "none",
  TypographyIosSmallSemiboldFontSize: 13,
  TypographyIosSmallSemiboldTextDecoration: "none",
  TypographyIosSmallSemiboldFontFamily: "SF Pro Text",
  TypographyIosSmallSemiboldFontWeight: 600,
  TypographyIosSmallSemiboldFontStyle: "normal",
  TypographyIosSmallSemiboldFontStretch: "normal",
  TypographyIosSmallSemiboldLetterSpacing: -0.08,
  TypographyIosSmallSemiboldLineHeight: 18,
  TypographyIosSmallSemiboldParagraphIndent: 0,
  TypographyIosSmallSemiboldParagraphSpacing: 0,
  TypographyIosSmallSemiboldTextCase: "none",
  TypographyIosXSmallRegularFontSize: 11,
  TypographyIosXSmallRegularTextDecoration: "none",
  TypographyIosXSmallRegularFontFamily: "SF Pro Text",
  TypographyIosXSmallRegularFontWeight: 400,
  TypographyIosXSmallRegularFontStyle: "normal",
  TypographyIosXSmallRegularFontStretch: "normal",
  TypographyIosXSmallRegularLetterSpacing: 0.07,
  TypographyIosXSmallRegularLineHeight: 13,
  TypographyIosXSmallRegularParagraphIndent: 0,
  TypographyIosXSmallRegularParagraphSpacing: 0,
  TypographyIosXSmallRegularTextCase: "none",
  TypographyIosXSmallSemiboldFontSize: 11,
  TypographyIosXSmallSemiboldTextDecoration: "none",
  TypographyIosXSmallSemiboldFontFamily: "SF Pro Text",
  TypographyIosXSmallSemiboldFontWeight: 600,
  TypographyIosXSmallSemiboldFontStyle: "normal",
  TypographyIosXSmallSemiboldFontStretch: "normal",
  TypographyIosXSmallSemiboldLetterSpacing: 0.07,
  TypographyIosXSmallSemiboldLineHeight: 13,
  TypographyIosXSmallSemiboldParagraphIndent: 0,
  TypographyIosXSmallSemiboldParagraphSpacing: 0,
  TypographyIosXSmallSemiboldTextCase: "none",
  TypographyIosMonospaceLargeFontSize: 17,
  TypographyIosMonospaceLargeTextDecoration: "none",
  TypographyIosMonospaceLargeFontFamily: "SF Mono",
  TypographyIosMonospaceLargeFontWeight: 400,
  TypographyIosMonospaceLargeFontStyle: "normal",
  TypographyIosMonospaceLargeFontStretch: "normal",
  TypographyIosMonospaceLargeLetterSpacing: 0,
  TypographyIosMonospaceLargeLineHeight: 22,
  TypographyIosMonospaceLargeParagraphIndent: 0,
  TypographyIosMonospaceLargeParagraphSpacing: 0,
  TypographyIosMonospaceLargeTextCase: "none",
  TypographyIosMonospaceDefaultFontSize: 15,
  TypographyIosMonospaceDefaultTextDecoration: "none",
  TypographyIosMonospaceDefaultFontFamily: "SF Mono",
  TypographyIosMonospaceDefaultFontWeight: 400,
  TypographyIosMonospaceDefaultFontStyle: "normal",
  TypographyIosMonospaceDefaultFontStretch: "normal",
  TypographyIosMonospaceDefaultLetterSpacing: 0,
  TypographyIosMonospaceDefaultLineHeight: 20,
  TypographyIosMonospaceDefaultParagraphIndent: 0,
  TypographyIosMonospaceDefaultParagraphSpacing: 0,
  TypographyIosMonospaceDefaultTextCase: "none",
  TypographyIosMonospaceSmallFontSize: 13,
  TypographyIosMonospaceSmallTextDecoration: "none",
  TypographyIosMonospaceSmallFontFamily: "SF Mono",
  TypographyIosMonospaceSmallFontWeight: 400,
  TypographyIosMonospaceSmallFontStyle: "normal",
  TypographyIosMonospaceSmallFontStretch: "normal",
  TypographyIosMonospaceSmallLetterSpacing: 0,
  TypographyIosMonospaceSmallLineHeight: 18,
  TypographyIosMonospaceSmallParagraphIndent: 0,
  TypographyIosMonospaceSmallParagraphSpacing: 0,
  TypographyIosMonospaceSmallTextCase: "none",
  TypographyDesktopHeadingDisplay1FontSize: 52,
  TypographyDesktopHeadingDisplay1TextDecoration: "none",
  TypographyDesktopHeadingDisplay1FontFamily: "Poppins",
  TypographyDesktopHeadingDisplay1FontWeight: 500,
  TypographyDesktopHeadingDisplay1FontStyle: "normal",
  TypographyDesktopHeadingDisplay1FontStretch: "normal",
  TypographyDesktopHeadingDisplay1LetterSpacing: 0,
  TypographyDesktopHeadingDisplay1LineHeight: 78,
  TypographyDesktopHeadingDisplay1ParagraphIndent: 0,
  TypographyDesktopHeadingDisplay1ParagraphSpacing: 0,
  TypographyDesktopHeadingDisplay1TextCase: "none",
  TypographyDesktopHeadingDisplay2FontSize: 36,
  TypographyDesktopHeadingDisplay2TextDecoration: "none",
  TypographyDesktopHeadingDisplay2FontFamily: "Poppins",
  TypographyDesktopHeadingDisplay2FontWeight: 500,
  TypographyDesktopHeadingDisplay2FontStyle: "normal",
  TypographyDesktopHeadingDisplay2FontStretch: "normal",
  TypographyDesktopHeadingDisplay2LetterSpacing: 0,
  TypographyDesktopHeadingDisplay2LineHeight: 54,
  TypographyDesktopHeadingDisplay2ParagraphIndent: 0,
  TypographyDesktopHeadingDisplay2ParagraphSpacing: 0,
  TypographyDesktopHeadingDisplay2TextCase: "none",
  TypographyDesktopHeadingH1FontSize: 32,
  TypographyDesktopHeadingH1TextDecoration: "none",
  TypographyDesktopHeadingH1FontFamily: "Poppins",
  TypographyDesktopHeadingH1FontWeight: 500,
  TypographyDesktopHeadingH1FontStyle: "normal",
  TypographyDesktopHeadingH1FontStretch: "normal",
  TypographyDesktopHeadingH1LetterSpacing: 0,
  TypographyDesktopHeadingH1LineHeight: 48,
  TypographyDesktopHeadingH1ParagraphIndent: 0,
  TypographyDesktopHeadingH1ParagraphSpacing: 0,
  TypographyDesktopHeadingH1TextCase: "none",
  TypographyDesktopHeadingH2FontSize: 28,
  TypographyDesktopHeadingH2TextDecoration: "none",
  TypographyDesktopHeadingH2FontFamily: "Poppins",
  TypographyDesktopHeadingH2FontWeight: 500,
  TypographyDesktopHeadingH2FontStyle: "normal",
  TypographyDesktopHeadingH2FontStretch: "normal",
  TypographyDesktopHeadingH2LetterSpacing: 0,
  TypographyDesktopHeadingH2LineHeight: 40,
  TypographyDesktopHeadingH2ParagraphIndent: 0,
  TypographyDesktopHeadingH2ParagraphSpacing: 0,
  TypographyDesktopHeadingH2TextCase: "none",
  TypographyDesktopHeadingH3FontSize: 22,
  TypographyDesktopHeadingH3TextDecoration: "none",
  TypographyDesktopHeadingH3FontFamily: "Poppins",
  TypographyDesktopHeadingH3FontWeight: 500,
  TypographyDesktopHeadingH3FontStyle: "normal",
  TypographyDesktopHeadingH3FontStretch: "normal",
  TypographyDesktopHeadingH3LetterSpacing: 0,
  TypographyDesktopHeadingH3LineHeight: 32,
  TypographyDesktopHeadingH3ParagraphIndent: 0,
  TypographyDesktopHeadingH3ParagraphSpacing: 0,
  TypographyDesktopHeadingH3TextCase: "none",
  TypographyDesktopHeadingH4FontSize: 16,
  TypographyDesktopHeadingH4TextDecoration: "none",
  TypographyDesktopHeadingH4FontFamily: "Poppins",
  TypographyDesktopHeadingH4FontWeight: 600,
  TypographyDesktopHeadingH4FontStyle: "normal",
  TypographyDesktopHeadingH4FontStretch: "normal",
  TypographyDesktopHeadingH4LetterSpacing: 0,
  TypographyDesktopHeadingH4LineHeight: 24,
  TypographyDesktopHeadingH4ParagraphIndent: 0,
  TypographyDesktopHeadingH4ParagraphSpacing: 0,
  TypographyDesktopHeadingH4TextCase: "none",
  TypographyDesktopPrimaryLargeRegularFontSize: 16,
  TypographyDesktopPrimaryLargeRegularTextDecoration: "none",
  TypographyDesktopPrimaryLargeRegularFontFamily: "Poppins",
  TypographyDesktopPrimaryLargeRegularFontWeight: 400,
  TypographyDesktopPrimaryLargeRegularFontStyle: "normal",
  TypographyDesktopPrimaryLargeRegularFontStretch: "normal",
  TypographyDesktopPrimaryLargeRegularLetterSpacing: 0,
  TypographyDesktopPrimaryLargeRegularLineHeight: 28,
  TypographyDesktopPrimaryLargeRegularParagraphIndent: 0,
  TypographyDesktopPrimaryLargeRegularParagraphSpacing: 0,
  TypographyDesktopPrimaryLargeRegularTextCase: "none",
  TypographyDesktopPrimaryLargeSemiboldFontSize: 16,
  TypographyDesktopPrimaryLargeSemiboldTextDecoration: "none",
  TypographyDesktopPrimaryLargeSemiboldFontFamily: "Poppins",
  TypographyDesktopPrimaryLargeSemiboldFontWeight: 600,
  TypographyDesktopPrimaryLargeSemiboldFontStyle: "normal",
  TypographyDesktopPrimaryLargeSemiboldFontStretch: "normal",
  TypographyDesktopPrimaryLargeSemiboldLetterSpacing: 0,
  TypographyDesktopPrimaryLargeSemiboldLineHeight: 28,
  TypographyDesktopPrimaryLargeSemiboldParagraphIndent: 0,
  TypographyDesktopPrimaryLargeSemiboldParagraphSpacing: 0,
  TypographyDesktopPrimaryLargeSemiboldTextCase: "none",
  TypographyDesktopPrimaryDefaultRegularFontSize: 14,
  TypographyDesktopPrimaryDefaultRegularTextDecoration: "none",
  TypographyDesktopPrimaryDefaultRegularFontFamily: "Poppins",
  TypographyDesktopPrimaryDefaultRegularFontWeight: 400,
  TypographyDesktopPrimaryDefaultRegularFontStyle: "normal",
  TypographyDesktopPrimaryDefaultRegularFontStretch: "normal",
  TypographyDesktopPrimaryDefaultRegularLetterSpacing: 0,
  TypographyDesktopPrimaryDefaultRegularLineHeight: 24,
  TypographyDesktopPrimaryDefaultRegularParagraphIndent: 0,
  TypographyDesktopPrimaryDefaultRegularParagraphSpacing: 0,
  TypographyDesktopPrimaryDefaultRegularTextCase: "none",
  TypographyDesktopPrimaryDefaultSemiboldFontSize: 14,
  TypographyDesktopPrimaryDefaultSemiboldTextDecoration: "none",
  TypographyDesktopPrimaryDefaultSemiboldFontFamily: "Poppins",
  TypographyDesktopPrimaryDefaultSemiboldFontWeight: 600,
  TypographyDesktopPrimaryDefaultSemiboldFontStyle: "normal",
  TypographyDesktopPrimaryDefaultSemiboldFontStretch: "normal",
  TypographyDesktopPrimaryDefaultSemiboldLetterSpacing: 0,
  TypographyDesktopPrimaryDefaultSemiboldLineHeight: 24,
  TypographyDesktopPrimaryDefaultSemiboldParagraphIndent: 0,
  TypographyDesktopPrimaryDefaultSemiboldParagraphSpacing: 0,
  TypographyDesktopPrimaryDefaultSemiboldTextCase: "none",
  TypographyDesktopPrimarySmallRegularFontSize: 12,
  TypographyDesktopPrimarySmallRegularTextDecoration: "none",
  TypographyDesktopPrimarySmallRegularFontFamily: "Poppins",
  TypographyDesktopPrimarySmallRegularFontWeight: 400,
  TypographyDesktopPrimarySmallRegularFontStyle: "normal",
  TypographyDesktopPrimarySmallRegularFontStretch: "normal",
  TypographyDesktopPrimarySmallRegularLetterSpacing: 0,
  TypographyDesktopPrimarySmallRegularLineHeight: 18,
  TypographyDesktopPrimarySmallRegularParagraphIndent: 0,
  TypographyDesktopPrimarySmallRegularParagraphSpacing: 0,
  TypographyDesktopPrimarySmallRegularTextCase: "none",
  TypographyDesktopPrimarySmallSemiboldFontSize: 12,
  TypographyDesktopPrimarySmallSemiboldTextDecoration: "none",
  TypographyDesktopPrimarySmallSemiboldFontFamily: "Poppins",
  TypographyDesktopPrimarySmallSemiboldFontWeight: 600,
  TypographyDesktopPrimarySmallSemiboldFontStyle: "normal",
  TypographyDesktopPrimarySmallSemiboldFontStretch: "normal",
  TypographyDesktopPrimarySmallSemiboldLetterSpacing: 0,
  TypographyDesktopPrimarySmallSemiboldLineHeight: 18,
  TypographyDesktopPrimarySmallSemiboldParagraphIndent: 0,
  TypographyDesktopPrimarySmallSemiboldParagraphSpacing: 0,
  TypographyDesktopPrimarySmallSemiboldTextCase: "none",
  TypographyDesktopPrimaryXSmallRegularFontSize: 11,
  TypographyDesktopPrimaryXSmallRegularTextDecoration: "none",
  TypographyDesktopPrimaryXSmallRegularFontFamily: "Poppins",
  TypographyDesktopPrimaryXSmallRegularFontWeight: 400,
  TypographyDesktopPrimaryXSmallRegularFontStyle: "normal",
  TypographyDesktopPrimaryXSmallRegularFontStretch: "normal",
  TypographyDesktopPrimaryXSmallRegularLetterSpacing: 0,
  TypographyDesktopPrimaryXSmallRegularLineHeight: 16,
  TypographyDesktopPrimaryXSmallRegularParagraphIndent: 0,
  TypographyDesktopPrimaryXSmallRegularParagraphSpacing: 0,
  TypographyDesktopPrimaryXSmallRegularTextCase: "none",
  TypographyDesktopPrimaryXSmallSemiboldFontSize: 11,
  TypographyDesktopPrimaryXSmallSemiboldTextDecoration: "none",
  TypographyDesktopPrimaryXSmallSemiboldFontFamily: "Poppins",
  TypographyDesktopPrimaryXSmallSemiboldFontWeight: 600,
  TypographyDesktopPrimaryXSmallSemiboldFontStyle: "normal",
  TypographyDesktopPrimaryXSmallSemiboldFontStretch: "normal",
  TypographyDesktopPrimaryXSmallSemiboldLetterSpacing: 0,
  TypographyDesktopPrimaryXSmallSemiboldLineHeight: 16,
  TypographyDesktopPrimaryXSmallSemiboldParagraphIndent: 0,
  TypographyDesktopPrimaryXSmallSemiboldParagraphSpacing: 0,
  TypographyDesktopPrimaryXSmallSemiboldTextCase: "none",
  TypographyDesktopSecondaryLargeRegularFontSize: 16,
  TypographyDesktopSecondaryLargeRegularTextDecoration: "none",
  TypographyDesktopSecondaryLargeRegularFontFamily: "Manrope",
  TypographyDesktopSecondaryLargeRegularFontWeight: 500,
  TypographyDesktopSecondaryLargeRegularFontStyle: "normal",
  TypographyDesktopSecondaryLargeRegularFontStretch: "normal",
  TypographyDesktopSecondaryLargeRegularLetterSpacing: 0,
  TypographyDesktopSecondaryLargeRegularLineHeight: 28,
  TypographyDesktopSecondaryLargeRegularParagraphIndent: 0,
  TypographyDesktopSecondaryLargeRegularParagraphSpacing: 0,
  TypographyDesktopSecondaryLargeRegularTextCase: "none",
  TypographyDesktopSecondaryLargeSemiboldFontSize: 16,
  TypographyDesktopSecondaryLargeSemiboldTextDecoration: "none",
  TypographyDesktopSecondaryLargeSemiboldFontFamily: "Manrope",
  TypographyDesktopSecondaryLargeSemiboldFontWeight: 700,
  TypographyDesktopSecondaryLargeSemiboldFontStyle: "normal",
  TypographyDesktopSecondaryLargeSemiboldFontStretch: "normal",
  TypographyDesktopSecondaryLargeSemiboldLetterSpacing: 0,
  TypographyDesktopSecondaryLargeSemiboldLineHeight: 28,
  TypographyDesktopSecondaryLargeSemiboldParagraphIndent: 0,
  TypographyDesktopSecondaryLargeSemiboldParagraphSpacing: 0,
  TypographyDesktopSecondaryLargeSemiboldTextCase: "none",
  TypographyDesktopSecondaryDefaultRegularFontSize: 14,
  TypographyDesktopSecondaryDefaultRegularTextDecoration: "none",
  TypographyDesktopSecondaryDefaultRegularFontFamily: "Manrope",
  TypographyDesktopSecondaryDefaultRegularFontWeight: 500,
  TypographyDesktopSecondaryDefaultRegularFontStyle: "normal",
  TypographyDesktopSecondaryDefaultRegularFontStretch: "normal",
  TypographyDesktopSecondaryDefaultRegularLetterSpacing: 0,
  TypographyDesktopSecondaryDefaultRegularLineHeight: 24,
  TypographyDesktopSecondaryDefaultRegularParagraphIndent: 0,
  TypographyDesktopSecondaryDefaultRegularParagraphSpacing: 0,
  TypographyDesktopSecondaryDefaultRegularTextCase: "none",
  TypographyDesktopSecondaryDefaultSemiboldFontSize: 14,
  TypographyDesktopSecondaryDefaultSemiboldTextDecoration: "none",
  TypographyDesktopSecondaryDefaultSemiboldFontFamily: "Manrope",
  TypographyDesktopSecondaryDefaultSemiboldFontWeight: 700,
  TypographyDesktopSecondaryDefaultSemiboldFontStyle: "normal",
  TypographyDesktopSecondaryDefaultSemiboldFontStretch: "normal",
  TypographyDesktopSecondaryDefaultSemiboldLetterSpacing: 0,
  TypographyDesktopSecondaryDefaultSemiboldLineHeight: 24,
  TypographyDesktopSecondaryDefaultSemiboldParagraphIndent: 0,
  TypographyDesktopSecondaryDefaultSemiboldParagraphSpacing: 0,
  TypographyDesktopSecondaryDefaultSemiboldTextCase: "none",
  TypographyDesktopSecondarySmallRegularFontSize: 12,
  TypographyDesktopSecondarySmallRegularTextDecoration: "none",
  TypographyDesktopSecondarySmallRegularFontFamily: "Manrope",
  TypographyDesktopSecondarySmallRegularFontWeight: 500,
  TypographyDesktopSecondarySmallRegularFontStyle: "normal",
  TypographyDesktopSecondarySmallRegularFontStretch: "normal",
  TypographyDesktopSecondarySmallRegularLetterSpacing: 0,
  TypographyDesktopSecondarySmallRegularLineHeight: 18,
  TypographyDesktopSecondarySmallRegularParagraphIndent: 0,
  TypographyDesktopSecondarySmallRegularParagraphSpacing: 0,
  TypographyDesktopSecondarySmallRegularTextCase: "none",
  TypographyDesktopSecondarySmallSemiboldFontSize: 12,
  TypographyDesktopSecondarySmallSemiboldTextDecoration: "none",
  TypographyDesktopSecondarySmallSemiboldFontFamily: "Manrope",
  TypographyDesktopSecondarySmallSemiboldFontWeight: 700,
  TypographyDesktopSecondarySmallSemiboldFontStyle: "normal",
  TypographyDesktopSecondarySmallSemiboldFontStretch: "normal",
  TypographyDesktopSecondarySmallSemiboldLetterSpacing: 0,
  TypographyDesktopSecondarySmallSemiboldLineHeight: 18,
  TypographyDesktopSecondarySmallSemiboldParagraphIndent: 0,
  TypographyDesktopSecondarySmallSemiboldParagraphSpacing: 0,
  TypographyDesktopSecondarySmallSemiboldTextCase: "none",
  TypographyDesktopSecondaryXSmallDefaultFontSize: 11,
  TypographyDesktopSecondaryXSmallDefaultTextDecoration: "none",
  TypographyDesktopSecondaryXSmallDefaultFontFamily: "Manrope",
  TypographyDesktopSecondaryXSmallDefaultFontWeight: 500,
  TypographyDesktopSecondaryXSmallDefaultFontStyle: "normal",
  TypographyDesktopSecondaryXSmallDefaultFontStretch: "normal",
  TypographyDesktopSecondaryXSmallDefaultLetterSpacing: 0,
  TypographyDesktopSecondaryXSmallDefaultLineHeight: 16,
  TypographyDesktopSecondaryXSmallDefaultParagraphIndent: 0,
  TypographyDesktopSecondaryXSmallDefaultParagraphSpacing: 0,
  TypographyDesktopSecondaryXSmallDefaultTextCase: "none",
  TypographyDesktopSecondaryXSmallSemiboldFontSize: 11,
  TypographyDesktopSecondaryXSmallSemiboldTextDecoration: "none",
  TypographyDesktopSecondaryXSmallSemiboldFontFamily: "Manrope",
  TypographyDesktopSecondaryXSmallSemiboldFontWeight: 700,
  TypographyDesktopSecondaryXSmallSemiboldFontStyle: "normal",
  TypographyDesktopSecondaryXSmallSemiboldFontStretch: "normal",
  TypographyDesktopSecondaryXSmallSemiboldLetterSpacing: 0,
  TypographyDesktopSecondaryXSmallSemiboldLineHeight: 16,
  TypographyDesktopSecondaryXSmallSemiboldParagraphIndent: 0,
  TypographyDesktopSecondaryXSmallSemiboldParagraphSpacing: 0,
  TypographyDesktopSecondaryXSmallSemiboldTextCase: "none",
  TypographyDesktopMonospaceLargeFontSize: 16,
  TypographyDesktopMonospaceLargeTextDecoration: "none",
  TypographyDesktopMonospaceLargeFontFamily: "DM Mono",
  TypographyDesktopMonospaceLargeFontWeight: 400,
  TypographyDesktopMonospaceLargeFontStyle: "normal",
  TypographyDesktopMonospaceLargeFontStretch: "normal",
  TypographyDesktopMonospaceLargeLetterSpacing: 0,
  TypographyDesktopMonospaceLargeLineHeight: 24,
  TypographyDesktopMonospaceLargeParagraphIndent: 0,
  TypographyDesktopMonospaceLargeParagraphSpacing: 0,
  TypographyDesktopMonospaceLargeTextCase: "none",
  TypographyDesktopMonospaceDefaultFontSize: 14,
  TypographyDesktopMonospaceDefaultTextDecoration: "none",
  TypographyDesktopMonospaceDefaultFontFamily: "DM Mono",
  TypographyDesktopMonospaceDefaultFontWeight: 400,
  TypographyDesktopMonospaceDefaultFontStyle: "normal",
  TypographyDesktopMonospaceDefaultFontStretch: "normal",
  TypographyDesktopMonospaceDefaultLetterSpacing: 0,
  TypographyDesktopMonospaceDefaultLineHeight: 24,
  TypographyDesktopMonospaceDefaultParagraphIndent: 0,
  TypographyDesktopMonospaceDefaultParagraphSpacing: 0,
  TypographyDesktopMonospaceDefaultTextCase: "none",
  TypographyDesktopMonospaceSmallFontSize: 12,
  TypographyDesktopMonospaceSmallTextDecoration: "none",
  TypographyDesktopMonospaceSmallFontFamily: "DM Mono",
  TypographyDesktopMonospaceSmallFontWeight: 400,
  TypographyDesktopMonospaceSmallFontStyle: "normal",
  TypographyDesktopMonospaceSmallFontStretch: "normal",
  TypographyDesktopMonospaceSmallLetterSpacing: 0,
  TypographyDesktopMonospaceSmallLineHeight: 18,
  TypographyDesktopMonospaceSmallParagraphIndent: 0,
  TypographyDesktopMonospaceSmallParagraphSpacing: 0,
  TypographyDesktopMonospaceSmallTextCase: "none",
  TypographyMobileDisplayDisplay1FontSize: 32,
  TypographyMobileDisplayDisplay1TextDecoration: "none",
  TypographyMobileDisplayDisplay1FontFamily: "Poppins",
  TypographyMobileDisplayDisplay1FontWeight: 500,
  TypographyMobileDisplayDisplay1FontStyle: "normal",
  TypographyMobileDisplayDisplay1FontStretch: "normal",
  TypographyMobileDisplayDisplay1LetterSpacing: 0,
  TypographyMobileDisplayDisplay1LineHeight: 48,
  TypographyMobileDisplayDisplay1ParagraphIndent: 0,
  TypographyMobileDisplayDisplay1ParagraphSpacing: 0,
  TypographyMobileDisplayDisplay1TextCase: "none",
  TypographyMobileDisplayDisplay2FontSize: 28,
  TypographyMobileDisplayDisplay2TextDecoration: "none",
  TypographyMobileDisplayDisplay2FontFamily: "Poppins",
  TypographyMobileDisplayDisplay2FontWeight: 500,
  TypographyMobileDisplayDisplay2FontStyle: "normal",
  TypographyMobileDisplayDisplay2FontStretch: "normal",
  TypographyMobileDisplayDisplay2LetterSpacing: 0,
  TypographyMobileDisplayDisplay2LineHeight: 42,
  TypographyMobileDisplayDisplay2ParagraphIndent: 0,
  TypographyMobileDisplayDisplay2ParagraphSpacing: 0,
  TypographyMobileDisplayDisplay2TextCase: "none",
  TypographyMobileHeadingH1FontSize: 28,
  TypographyMobileHeadingH1TextDecoration: "none",
  TypographyMobileHeadingH1FontFamily: "Poppins",
  TypographyMobileHeadingH1FontWeight: 500,
  TypographyMobileHeadingH1FontStyle: "normal",
  TypographyMobileHeadingH1FontStretch: "normal",
  TypographyMobileHeadingH1LetterSpacing: 0,
  TypographyMobileHeadingH1LineHeight: 40,
  TypographyMobileHeadingH1ParagraphIndent: 0,
  TypographyMobileHeadingH1ParagraphSpacing: 0,
  TypographyMobileHeadingH1TextCase: "none",
  TypographyMobileHeadingH2FontSize: 22,
  TypographyMobileHeadingH2TextDecoration: "none",
  TypographyMobileHeadingH2FontFamily: "Poppins",
  TypographyMobileHeadingH2FontWeight: 500,
  TypographyMobileHeadingH2FontStyle: "normal",
  TypographyMobileHeadingH2FontStretch: "normal",
  TypographyMobileHeadingH2LetterSpacing: 0,
  TypographyMobileHeadingH2LineHeight: 32,
  TypographyMobileHeadingH2ParagraphIndent: 0,
  TypographyMobileHeadingH2ParagraphSpacing: 0,
  TypographyMobileHeadingH2TextCase: "none",
  TypographyMobileHeadingH3FontSize: 18,
  TypographyMobileHeadingH3TextDecoration: "none",
  TypographyMobileHeadingH3FontFamily: "Poppins",
  TypographyMobileHeadingH3FontWeight: 500,
  TypographyMobileHeadingH3FontStyle: "normal",
  TypographyMobileHeadingH3FontStretch: "normal",
  TypographyMobileHeadingH3LetterSpacing: 0,
  TypographyMobileHeadingH3LineHeight: 28,
  TypographyMobileHeadingH3ParagraphIndent: 0,
  TypographyMobileHeadingH3ParagraphSpacing: 0,
  TypographyMobileHeadingH3TextCase: "none",
  TypographyMobileHeadingH4FontSize: 16,
  TypographyMobileHeadingH4TextDecoration: "none",
  TypographyMobileHeadingH4FontFamily: "Poppins",
  TypographyMobileHeadingH4FontWeight: 600,
  TypographyMobileHeadingH4FontStyle: "normal",
  TypographyMobileHeadingH4FontStretch: "normal",
  TypographyMobileHeadingH4LetterSpacing: 0,
  TypographyMobileHeadingH4LineHeight: 24,
  TypographyMobileHeadingH4ParagraphIndent: 0,
  TypographyMobileHeadingH4ParagraphSpacing: 0,
  TypographyMobileHeadingH4TextCase: "none",
  TypographyComponentsLabelFontSize: 11,
  TypographyComponentsLabelTextDecoration: "none",
  TypographyComponentsLabelFontFamily: "Poppins",
  TypographyComponentsLabelFontWeight: 500,
  TypographyComponentsLabelFontStyle: "normal",
  TypographyComponentsLabelFontStretch: "normal",
  TypographyComponentsLabelLetterSpacing: 0.22,
  TypographyComponentsLabelLineHeight: 13.2,
  TypographyComponentsLabelParagraphIndent: 0,
  TypographyComponentsLabelParagraphSpacing: 0,
  TypographyComponentsLabelTextCase: "none",
  TypographyComponentsTableheaderFontSize: 13,
  TypographyComponentsTableheaderTextDecoration: "none",
  TypographyComponentsTableheaderFontFamily: "Poppins",
  TypographyComponentsTableheaderFontWeight: 500,
  TypographyComponentsTableheaderFontStyle: "normal",
  TypographyComponentsTableheaderFontStretch: "normal",
  TypographyComponentsTableheaderLetterSpacing: 0,
  TypographyComponentsTableheaderLineHeight: 20,
  TypographyComponentsTableheaderParagraphIndent: 0,
  TypographyComponentsTableheaderParagraphSpacing: 0,
  TypographyComponentsTableheaderTextCase: "none",
  TypographyComponentsNavbuttonFontSize: 15,
  TypographyComponentsNavbuttonTextDecoration: "none",
  TypographyComponentsNavbuttonFontFamily: "Poppins",
  TypographyComponentsNavbuttonFontWeight: 600,
  TypographyComponentsNavbuttonFontStyle: "normal",
  TypographyComponentsNavbuttonFontStretch: "normal",
  TypographyComponentsNavbuttonLetterSpacing: 0.3,
  TypographyComponentsNavbuttonLineHeight: 20,
  TypographyComponentsNavbuttonParagraphIndent: 0,
  TypographyComponentsNavbuttonParagraphSpacing: 0,
  TypographyComponentsNavbuttonTextCase: "none",
  TypographyComponentsButtonSmallFontSize: 12,
  TypographyComponentsButtonSmallTextDecoration: "none",
  TypographyComponentsButtonSmallFontFamily: "Poppins",
  TypographyComponentsButtonSmallFontWeight: 600,
  TypographyComponentsButtonSmallFontStyle: "normal",
  TypographyComponentsButtonSmallFontStretch: "normal",
  TypographyComponentsButtonSmallLetterSpacing: 0.36,
  TypographyComponentsButtonSmallLineHeight: 16,
  TypographyComponentsButtonSmallParagraphIndent: 0,
  TypographyComponentsButtonSmallParagraphSpacing: 0,
  TypographyComponentsButtonSmallTextCase: "none",
  TypographyComponentsButtonDefaultFontSize: 13,
  TypographyComponentsButtonDefaultTextDecoration: "none",
  TypographyComponentsButtonDefaultFontFamily: "Poppins",
  TypographyComponentsButtonDefaultFontWeight: 600,
  TypographyComponentsButtonDefaultFontStyle: "normal",
  TypographyComponentsButtonDefaultFontStretch: "normal",
  TypographyComponentsButtonDefaultLetterSpacing: 0.39,
  TypographyComponentsButtonDefaultLineHeight: 20,
  TypographyComponentsButtonDefaultParagraphIndent: 0,
  TypographyComponentsButtonDefaultParagraphSpacing: 0,
  TypographyComponentsButtonDefaultTextCase: "none",
  TypographyComponentsButtonLargeFontSize: 14,
  TypographyComponentsButtonLargeTextDecoration: "none",
  TypographyComponentsButtonLargeFontFamily: "Poppins",
  TypographyComponentsButtonLargeFontWeight: 600,
  TypographyComponentsButtonLargeFontStyle: "normal",
  TypographyComponentsButtonLargeFontStretch: "normal",
  TypographyComponentsButtonLargeLetterSpacing: 0.28,
  TypographyComponentsButtonLargeLineHeight: 20,
  TypographyComponentsButtonLargeParagraphIndent: 0,
  TypographyComponentsButtonLargeParagraphSpacing: 0,
  TypographyComponentsButtonLargeTextCase: "none",
  TypographyComponentsButtonJumboFontSize: 16,
  TypographyComponentsButtonJumboTextDecoration: "none",
  TypographyComponentsButtonJumboFontFamily: "Poppins",
  TypographyComponentsButtonJumboFontWeight: 600,
  TypographyComponentsButtonJumboFontStyle: "normal",
  TypographyComponentsButtonJumboFontStretch: "normal",
  TypographyComponentsButtonJumboLetterSpacing: 0.16,
  TypographyComponentsButtonJumboLineHeight: 24,
  TypographyComponentsButtonJumboParagraphIndent: 0,
  TypographyComponentsButtonJumboParagraphSpacing: 0,
  TypographyComponentsButtonJumboTextCase: "none",
  ColorLightIconbackgroundHover: "#131620",
  ColorLightIconbackgroundActive: "#131620",
  ColorLightIconTint: "#0b1641",
  ColorLightFrostedGlass: "#fcfcfd",
  ColorLightFrostedGlassDivider: "#16171d",
  ColorLightTextPrimary: "#1c1e26",
  ColorLightTextSecondary: "#666d89",
  ColorLightTextTertiary: "#7e85a0",
  ColorLightTextInteractive: "#423eee",
  ColorLightTextDisabled: "#1c1f26",
  ColorLightIconDefault: "#666d89",
  ColorLightIconInteractive: "#5f5cf1",
  ColorLightIconDisabled: "#666d89",
  ColorLightInteractionButtonPrimaryBackground: "#423eee",
  ColorLightPageBackground: "#f5f5f7",
  ColorLightContainerBackground: "#ffffff",
  ColorLightContainerHighlight: "#f0f1f4",
  ColorLightContainerInteractiveBackground: "#f2f1fe",
  ColorLightContainerDisabled: "#a8adbf",
  ColorLightModalScreenBackground: "#111217",
  ColorLightDividerSubtle: "#e8e9ee",
  ColorLightDividerStrong: "#c4c7d4",
  ColorLightSystemfeedbackInfoBackground: "#f0f7fc",
  ColorLightSystemfeedbackInfoIcon: "#0f75c9",
  ColorLightSystemfeedbackErrorBackground: "#fdf3f5",
  ColorLightSystemfeedbackErrorIcon: "#dc1d3c",
  ColorLightSystemfeedbackWarningBackground: "#fff4d8",
  ColorLightSystemfeedbackWarningIcon: "#e2a500",
  ColorLightSystemfeedbackSuccessBackground: "#e8f9eb",
  ColorLightSystemfeedbackSuccessIcon: "#31803e",
  ColorLightGray10: "#f5f5f7",
  ColorLightGray20: "#e1e2e8",
  ColorLightGray30: "#a8adbf",
  ColorLightGray40: "#666d89",
  ColorLightGray50: "#545a71",
  ColorLightGray60: "#3f4355",
  ColorLightGray70: "#1c1e26",
  ColorLightPrimary10: "#f5f4fe",
  ColorLightPrimary20: "#e2e2fc",
  ColorLightPrimary30: "#aaa8f7",
  ColorLightPrimary40: "#5f5cf1",
  ColorLightPrimary50: "#423eee",
  ColorLightPrimary60: "#322fb4",
  ColorLightPrimary70: "#171553",
  ColorLightSecondary10: "#fdf4f2",
  ColorLightSecondary20: "#feded6",
  ColorLightSecondary30: "#fc9378",
  ColorLightSecondary40: "#fe5907",
  ColorLightSecondary50: "#b22603",
  ColorLightSecondary60: "#861d03",
  ColorLightSecondary70: "#3f0e01",
  ColorLightRed10: "#fdf3f5",
  ColorLightRed20: "#fbdde2",
  ColorLightRed30: "#f195a4",
  ColorLightRed40: "#dc1d3c",
  ColorLightRed50: "#b81832",
  ColorLightRed60: "#8a1226",
  ColorLightRed70: "#410912",
  ColorLightYellow10: "#fff4d8",
  ColorLightYellow20: "#ffe193",
  ColorLightYellow30: "#e2a500",
  ColorLightYellow40: "#926a00",
  ColorLightYellow50: "#785700",
  ColorLightYellow60: "#5a4100",
  ColorLightYellow70: "#281d00",
  ColorLightGreen10: "#e8f9eb",
  ColorLightGreen20: "#c2eec9",
  ColorLightGreen30: "#4dc661",
  ColorLightGreen40: "#31803e",
  ColorLightGreen50: "#296933",
  ColorLightGreen60: "#1f4f27",
  ColorLightGreen70: "#0e2311",
  ColorLightTeal10: "#eff7f8",
  ColorLightTeal20: "#d1e8eb",
  ColorLightTeal30: "#76bac2",
  ColorLightTeal40: "#007c8a",
  ColorLightTeal50: "#006772",
  ColorLightTeal60: "#004d56",
  ColorLightTeal70: "#002327",
  ColorLightBlue10: "#f0f7fc",
  ColorLightBlue20: "#d0e8fc",
  ColorLightBlue30: "#6ab6f4",
  ColorLightBlue40: "#0f75c9",
  ColorLightBlue50: "#0c5fa3",
  ColorLightBlue60: "#09477a",
  ColorLightBlue70: "#042038",
  ColorLightPurple10: "#f5f6fc",
  ColorLightPurple20: "#e1e3f7",
  ColorLightPurple30: "#a6abe8",
  ColorLightPurple40: "#5d65d3",
  ColorLightPurple50: "#4c53ad",
  ColorLightPurple60: "#393e82",
  ColorLightPurple70: "#1a1c3b",
  ColorLightPink10: "#fdf3f8",
  ColorLightPink20: "#fadbec",
  ColorLightPink30: "#f092c5",
  ColorLightPink40: "#d41c80",
  ColorLightPink50: "#af1768",
  ColorLightPink60: "#851150",
  ColorLightPink70: "#3f0826",
  ColorLightPrivateWindow10: "#f5f4fa",
  ColorLightPrivateWindow20: "#e5e2f0",
  ColorLightPrivateWindow30: "#b3aad3",
  ColorLightPrivateWindow40: "#7566b0",
  ColorLightPrivateWindow50: "#614fa4",
  ColorLightPrivateWindow60: "#483396",
  ColorLightPrivateWindow70: "#1e0d5e",
  ColorLightTorWindow10: "#f8f5fa",
  ColorLightTorWindow20: "#ebe1f0",
  ColorLightTorWindow30: "#c2a5d1",
  ColorLightTorWindow40: "#915ead",
  ColorLightTorWindow50: "#784a91",
  ColorLightTorWindow60: "#5a376c",
  ColorLightTorWindow70: "#271a2f",
  ColorDarkIconbackgroundHover: "#0a0b10",
  ColorDarkIconbackgroundActive: "#0a0b10",
  ColorDarkIconTint: "#b1b7cd",
  ColorDarkFrostedGlass: "#181a20",
  ColorDarkFrostedGlassDivider: "#0b0c0f",
  ColorDarkTextPrimary: "#edeef1",
  ColorDarkTextSecondary: "#878da6",
  ColorDarkTextTertiary: "#616884",
  ColorDarkTextInteractive: "#aaa8f7",
  ColorDarkTextDisabled: "#edeef1",
  ColorDarkIconDefault: "#878da6",
  ColorDarkIconInteractive: "#8784f4",
  ColorDarkIconDisabled: "#878da6",
  ColorDarkInteractionButtonPrimaryBackground: "#423eee",
  ColorDarkPageBackground: "#09090c",
  ColorDarkContainerBackground: "#191b22",
  ColorDarkContainerHighlight: "#0d0e12",
  ColorDarkContainerInteractiveBackground: "#0e0e34",
  ColorDarkContainerDisabled: "#545a71",
  ColorDarkModalScreenBackground: "#111217",
  ColorDarkDividerSubtle: "#2b2e3b",
  ColorDarkDividerStrong: "#3b3f4f",
  ColorDarkSystemfeedbackInfoBackground: "#052743",
  ColorDarkSystemfeedbackInfoIcon: "#2795ef",
  ColorDarkSystemfeedbackErrorBackground: "#440912",
  ColorDarkSystemfeedbackErrorIcon: "#eb637a",
  ColorDarkSystemfeedbackWarningBackground: "#332500",
  ColorDarkSystemfeedbackWarningIcon: "#bb8800",
  ColorDarkSystemfeedbackSuccessBackground: "#102914",
  ColorDarkSystemfeedbackSuccessIcon: "#3fa450",
  ColorDarkGray10: "#111217",
  ColorDarkGray20: "#262a33",
  ColorDarkGray30: "#545a71",
  ColorDarkGray40: "#878da6",
  ColorDarkGray50: "#a8adbf",
  ColorDarkGray60: "#c3c6d3",
  ColorDarkGray70: "#edeef1",
  ColorDarkPrimary10: "#0e0e34",
  ColorDarkPrimary20: "#23217f",
  ColorDarkPrimary30: "#423eee",
  ColorDarkPrimary40: "#8784f4",
  ColorDarkPrimary50: "#aaa8f7",
  ColorDarkPrimary60: "#c5c4fa",
  ColorDarkPrimary70: "#efeefe",
  ColorDarkSecondary10: "#280901",
  ColorDarkSecondary20: "#5f1402",
  ColorDarkSecondary30: "#b22603",
  ColorDarkSecondary40: "#fb5930",
  ColorDarkSecondary50: "#fc9378",
  ColorDarkSecondary60: "#fdb7a5",
  ColorDarkSecondary70: "#fcece8",
  ColorDarkRed10: "#2a060b",
  ColorDarkRed20: "#630d1b",
  ColorDarkRed30: "#b81832",
  ColorDarkRed40: "#eb637a",
  ColorDarkRed50: "#f195a4",
  ColorDarkRed60: "#f6b8c2",
  ColorDarkRed70: "#fceaed",
  ColorDarkYellow10: "#191200",
  ColorDarkYellow20: "#3f2e00",
  ColorDarkYellow30: "#785700",
  ColorDarkYellow40: "#bb8800",
  ColorDarkYellow50: "#e2a500",
  ColorDarkYellow60: "#febf17",
  ColorDarkYellow70: "#ffeec1",
  ColorDarkGreen10: "#08160b",
  ColorDarkGreen20: "#15371b",
  ColorDarkGreen30: "#296933",
  ColorDarkGreen40: "#3fa450",
  ColorDarkGreen50: "#4dc661",
  ColorDarkGreen60: "#81dc90",
  ColorDarkGreen70: "#dbf5df",
  ColorDarkTeal10: "#001619",
  ColorDarkTeal20: "#00363c",
  ColorDarkTeal30: "#006772",
  ColorDarkTeal40: "#3d9ea8",
  ColorDarkTeal50: "#76bac2",
  ColorDarkTeal60: "#a4d1d6",
  ColorDarkTeal70: "#e3f1f2",
  ColorDarkBlue10: "#021523",
  ColorDarkBlue20: "#063256",
  ColorDarkBlue30: "#0c5fa3",
  ColorDarkBlue40: "#2795ef",
  ColorDarkBlue50: "#6ab6f4",
  ColorDarkBlue60: "#9bcef8",
  ColorDarkBlue70: "#e4f0f9",
  ColorDarkPurple10: "#101124",
  ColorDarkPurple20: "#282c5a",
  ColorDarkPurple30: "#4c53ad",
  ColorDarkPurple40: "#8389df",
  ColorDarkPurple50: "#a6abe8",
  ColorDarkPurple60: "#c3c6f0",
  ColorDarkPurple70: "#edeefa",
  ColorDarkPink10: "#290519",
  ColorDarkPink20: "#5f0c39",
  ColorDarkPink30: "#af1769",
  ColorDarkPink40: "#e85fa9",
  ColorDarkPink50: "#f092c5",
  ColorDarkPink60: "#f5b6d8",
  ColorDarkPink70: "#fce9f3",
  ColorDarkPrivateWindow10: "#1e0d5e",
  ColorDarkPrivateWindow20: "#483396",
  ColorDarkPrivateWindow30: "#614fa4",
  ColorDarkPrivateWindow40: "#7566b0",
  ColorDarkPrivateWindow50: "#b3aad3",
  ColorDarkPrivateWindow60: "#e5e2f0",
  ColorDarkPrivateWindow70: "#f5f4fa",
  ColorDarkTorWindow10: "#18101d",
  ColorDarkTorWindow20: "#3f274c",
  ColorDarkTorWindow30: "#784a91",
  ColorDarkTorWindow40: "#a981bf",
  ColorDarkTorWindow50: "#c2a5d1",
  ColorDarkTorWindow60: "#d5c2e0",
  ColorDarkTorWindow70: "#f2edf5",
  ColorLegacyLightBackground1: "#ffffff",
  ColorLegacyLightBackground2: "#f8f9fa",
  ColorLegacyLightText1: "#212529",
  ColorLegacyLightText2: "#495057",
  ColorLegacyLightText3: "#868e96",
  ColorLegacyLightInteractive1: "#ea3a0d",
  ColorLegacyLightInteractive2: "#fb542b",
  ColorLegacyLightInteractive3: "#ff7654",
  ColorLegacyLightInteractive4: "#353dab",
  ColorLegacyLightInteractive5: "#4c54d2",
  ColorLegacyLightInteractive6: "#737ade",
  ColorLegacyLightInteractive7: "#212529",
  ColorLegacyLightInteractive8: "#aeb1c2",
  ColorLegacyLightDisabled: "#dadce8",
  ColorLegacyLightFocusBorder: "#a0a5eb",
  ColorLegacyLightDivider1: "#e9e9f4",
  ColorLegacyDarkBackground1: "#1e2029",
  ColorLegacyDarkBackground2: "#17171f",
  ColorLegacyDarkText1: "#f0f2ff",
  ColorLegacyDarkText2: "#c2c4cf",
  ColorLegacyDarkText3: "#84889c",
  ColorLegacyDarkInteractive1: "#ea3a0d",
  ColorLegacyDarkInteractive2: "#fb542b",
  ColorLegacyDarkInteractive3: "#ff7654",
  ColorLegacyDarkInteractive4: "#353dab",
  ColorLegacyDarkInteractive5: "#4c54d2",
  ColorLegacyDarkInteractive6: "#737ade",
  ColorLegacyDarkInteractive7: "#f0f2ff",
  ColorLegacyDarkInteractive8: "#5e6175",
  ColorLegacyDarkDisabled: "#343a40",
  ColorLegacyDarkFocusBorder: "#a0a5eb",
  ColorLegacyDarkDivider1: "#3b3e4f",
  ColorPrivateContainerHighlight: "#110736",
  ColorWhite: "#ffffff",
  ColorBlack: "#000000",
  ColorLogosBat1: "#ff4724",
  ColorLogosBat2: "#9e1f63",
  ColorLogosBat3: "#662d91",
  Spacing4: { top: 4, bottom: 4, left: 4, right: 4 },
  Spacing8: { top: 8, bottom: 8, left: 8, right: 8 },
  Spacing12: { top: 12, bottom: 12, left: 12, right: 12 },
  Spacing16: { top: 16, bottom: 16, left: 16, right: 16 },
  Spacing24: { top: 24, bottom: 24, left: 24, right: 24 },
  Spacing32: { top: 32, bottom: 32, left: 32, right: 32 },
  Spacing40: { top: 40, bottom: 40, left: 40, right: 40 },
  Radius1: {
    smoothing: 0.61,
    topLeft: 1,
    topRight: 1,
    bottomLeft: 1,
    bottomRight: 1,
  },
  Radius2: {
    smoothing: 0.61,
    topLeft: 2,
    topRight: 2,
    bottomLeft: 2,
    bottomRight: 2,
  },
  Radius4: {
    smoothing: 0.61,
    topLeft: 3,
    topRight: 3,
    bottomLeft: 3,
    bottomRight: 3,
  },
  Radius8: {
    smoothing: 0.61,
    topLeft: 8,
    topRight: 8,
    bottomLeft: 8,
    bottomRight: 8,
  },
  Radius12: {
    smoothing: 0.61,
    topLeft: 8,
    topRight: 8,
    bottomLeft: 8,
    bottomRight: 8,
  },
  Radius16: {
    smoothing: 0.61,
    topLeft: 16,
    topRight: 16,
    bottomLeft: 16,
    bottomRight: 16,
  },
  RadiusFull: {
    smoothing: 0.61,
    topLeft: 100,
    topRight: 100,
    bottomLeft: 100,
    bottomRight: 100,
  },
  Grid0560Breakpoint: {
    pattern: "columns",
    gutterSize: 16,
    alignment: "stretch",
    count: 6,
    offset: 0,
  },
  Grid561820Breakpoint: {
    pattern: "columns",
    gutterSize: 16,
    alignment: "stretch",
    count: 8,
    offset: 16,
  },
  Grid8211140Breakpoint: {
    pattern: "columns",
    gutterSize: 16,
    alignment: "stretch",
    count: 12,
    offset: 16,
  },
  Grid1141Breakpoint: {
    pattern: "columns",
    gutterSize: 24,
    alignment: "stretch",
    count: 12,
    offset: 24,
  },
  EffectFocusState: [
    {
      shadowType: "dropShadow",
      radius: 0,
      color: "#ffffff80",
      offsetX: 0,
      offsetY: 0,
      spread: 1.5,
    },
    {
      shadowType: "dropShadow",
      radius: 4,
      color: "#423eeeff",
      offsetX: 0,
      offsetY: 0,
      spread: 2,
    },
  ],
  EffectElevationLight01: {
    shadowType: "dropShadow",
    radius: 4,
    color: "#00000012",
    offsetX: 0,
    offsetY: 1,
    spread: 0,
  },
  EffectElevationLight02: {
    shadowType: "dropShadow",
    radius: 10,
    color: "#0000000f",
    offsetX: 0,
    offsetY: 3,
    spread: -1,
  },
  EffectElevationLight03: {
    shadowType: "dropShadow",
    radius: 13,
    color: "#00000014",
    offsetX: 0,
    offsetY: 4,
    spread: -2,
  },
  EffectElevationLight04: {
    shadowType: "dropShadow",
    radius: 16,
    color: "#00000012",
    offsetX: 0,
    offsetY: 4,
    spread: -1,
  },
  EffectElevationLight05: {
    shadowType: "dropShadow",
    radius: 25,
    color: "#00000012",
    offsetX: 0,
    offsetY: 6,
    spread: -2,
  },
  EffectElevationLight06: {
    shadowType: "dropShadow",
    radius: 32,
    color: "#0000000f",
    offsetX: 0,
    offsetY: 10,
    spread: 0,
  },
  EffectElevationLight07: {
    shadowType: "dropShadow",
    radius: 40,
    color: "#00000014",
    offsetX: 0,
    offsetY: 8,
    spread: 0,
  },
  EffectElevationDark01: {
    shadowType: "dropShadow",
    radius: 4,
    color: "#00000066",
    offsetX: 0,
    offsetY: 1,
    spread: 0,
  },
  EffectElevationDark02: {
    shadowType: "dropShadow",
    radius: 10,
    color: "#00000059",
    offsetX: 0,
    offsetY: 3,
    spread: -1,
  },
  EffectElevationDark03: {
    shadowType: "dropShadow",
    radius: 13,
    color: "#00000059",
    offsetX: 0,
    offsetY: 4,
    spread: -2,
  },
  EffectElevationDark04: {
    shadowType: "dropShadow",
    radius: 16,
    color: "#00000059",
    offsetX: 0,
    offsetY: 4,
    spread: -1,
  },
  EffectElevationDark05: {
    shadowType: "dropShadow",
    radius: 25,
    color: "#00000059",
    offsetX: 0,
    offsetY: 6,
    spread: -2,
  },
  EffectElevationDark06: {
    shadowType: "dropShadow",
    radius: 32,
    color: "#00000059",
    offsetX: 0,
    offsetY: 10,
    spread: 0,
  },
  EffectElevationDark07: {
    shadowType: "dropShadow",
    radius: 40,
    color: "#00000059",
    offsetX: 0,
    offsetY: 8,
    spread: 0,
  },
  GradientHero: {
    gradientType: "linear",
    rotation: 138.21219643124405,
    stops: [
      { position: 0.22, color: "#8b10c6ff" },
      { position: 0.7, color: "#d02480ff" },
      { position: 0.96, color: "#e95e3cff" },
    ],
  },
  GradientIconsActive: {
    gradientType: "linear",
    rotation: 321.5013256215316,
    stops: [
      { position: 0.03, color: "#fa7250ff" },
      { position: 0.4, color: "#ff1893ff" },
      { position: 0.99, color: "#a78affff" },
    ],
  },
  GradientPanelBackground: {
    gradientType: "linear",
    rotation: 134.9999995731132,
    stops: [
      { position: 0, color: "#322fb4ff" },
      { position: 1, color: "#423eeeff" },
    ],
  },
  GradientPanelBackgroundAlternative: {
    gradientType: "linear",
    rotation: 134.9999995731132,
    stops: [
      { position: 0, color: "#514de0ff" },
      { position: 1, color: "#af1768ff" },
    ],
  },
  GradientToolbarBackground: {
    gradientType: "linear",
    rotation: 134.9999995731132,
    stops: [
      { position: 0, color: "#e7304fff" },
      { position: 1, color: "#b20f96ff" },
    ],
  },
  GradientBraveRelease: {
    gradientType: "linear",
    rotation: 90,
    stops: [
      { position: 0, color: "#ff5500ff" },
      { position: 0.33, color: "#ff5500ff" },
      { position: 0.67, color: "#ff2000ff" },
      { position: 1, color: "#ff2000ff" },
    ],
  },
  GradientBraveBeta: {
    gradientType: "linear",
    rotation: 90,
    stops: [
      { position: 0, color: "#0099e5ff" },
      { position: 0.5, color: "#0059b2ff" },
      { position: 1, color: "#002b80ff" },
    ],
  },
  GradientBraveNightly: {
    gradientType: "linear",
    rotation: 90,
    stops: [
      { position: 0, color: "#901ee1ff" },
      { position: 0.51, color: "#65149eff" },
      { position: 1, color: "#480f71ff" },
    ],
  },
  GradientBraveDebug: {
    gradientType: "linear",
    rotation: 90,
    stops: [
      { position: 0, color: "#6c7493ff" },
      { position: 0.51, color: "#575d75ff" },
      { position: 1, color: "#363a49ff" },
    ],
  },
};
